### ISSUE TITLE
I am having issues with the DocSearch dependency of `@markprompt/core` 

### ISSUE THREAD

**Issue by nckhell** [motifland/markprompt-js#156]
**Describe the bug**
I have imported `@markprompt/core` in my project

```package.json
{
  "name": "awell-website",
  "sideEffects": false,
  "type": "module",
  "dependencies": {
    "@markprompt/core": "^0.11.0"
  },
  ...
}
```

I get the following error:
<img width="831" alt="Screenshot 2023-08-30 at 12 39 21" src="https://github.com/motifland/markprompt-js/assets/5594064/69ca462d-b841-4312-ab34-a403b28b3d5f">

DocSearch is not a dependency that's in my own project so I checked and it's a dependency of `@markprompt/core` ([see package.json](https://github.com/motifland/markprompt-js/blob/main/packages/core/package.json)). The file that causes the issue is `@docsearch/react/dist/esm/types/DocSearchHit.js:1` which is imported in [this file](https://github.com/motifland/markprompt-js/blob/main/packages/core/src/types.ts) of `@markprompt/core`.

**Expected behavior**
No error for that docsearch dependency. Seems to be an issue with ESM imports/modules.

**Additional context**
- Node version: v18.16.1
- NextJS version: 12.0.8

**Comment by nickrttn** [comment]
@nckhell Thanks for reporting the issue. Looking into it now.

**Comment by nickrttn** [comment]
@nckhell Ok, I dove into this a bit and as far as I can tell this happens because Next.js 12 doesn't support transpiling ESM from `node_modules` just yet. You can work around the error by making sure `@markprompt/core` is being transpiled by Next.js. For that you have two options:

**Option 1**

- Install `next-transpile-modules@9.x`
- Update `next.config.js`:

```js
const withTM = require('next-transpile-modules')(['@markprompt/core']); // pass the modules you would like to see transpiled

module.exports = withTM({
  ...your config
})
```

**Option 2**

- Upgrade to at least Next.js 13.1
- Update `next.config.js`:

```js
module.exports = {
  transpilePackages: ['@markprompt/core'],
};
```

**Comment by nckhell** [comment]
Thanks @nickrttn, I have installed `next-transpile-modules` and that did the trick!
